/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package kamon.zipkin.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class zipkinConstants {

  public static final String CLIENT_SEND = "cs";

  public static final String CLIENT_RECV = "cr";

  public static final String SERVER_SEND = "ss";

  public static final String SERVER_RECV = "sr";

  public static final String SERVER_ADDR = "sa";

  public static final String CLIENT_ADDR = "ca";

  public static final String CLIENT_SEND_FRAGMENT = "csf";

  public static final String CLIENT_RECV_FRAGMENT = "crf";

  public static final String SERVER_SEND_FRAGMENT = "ssf";

  public static final String SERVER_RECV_FRAGMENT = "srf";

}
